### ISSUE TITLE
reflection works with grpcurl but not grpcui

### ISSUE THREAD

**Issue by robertwenquan** [connectrpc/grpcreflect-go#75]
grpcurl list and grpcurl describe both work, but the grpcui throws error
```
grpcui -plaintext localhost:8080
Failed to compute set of methods to expose: server does not support the reflection API
```

The grpcurl works

```
grpcurl -plaintext localhost:8080 list
api.v1.APIService
```

```
grpcurl -plaintext localhost:8080 describe
api.v1.APIService is a service:
service APIService {
  ....omitted....
}
```

version info

```
$ grpcui --version
grpcui 1.4.1

$ grpcurl --version
grpcurl dev build <no version set>
```

reflection error comes up with postman as well.

<img width="583" alt="image" src="https://github.com/connectrpc/grpcreflect-go/assets/8893623/b0c88c3b-6304-4fe1-8b6c-9cbc46a5264b">

**Comment by akshayjshah** [comment]
It looks like `grpcui` hasn't been updated to use v1 of the reflection API. Is your code also exposing v1alpha1 of the reflection API (using `grpcreflect.NewHandlerV1Alpha`)?

**Comment by robertwenquan** [comment]
Good point. @akshayjshah You are right I didn't add the `grpcreflect.NewHandlerV1Alpha(reflector)` line. So it looks both grpcui and postman haven't updated the reflection API in their clients.

After adding this line, both the grpcui and postman work now. Thanks a ton!

<img width="759" alt="image" src="https://github.com/connectrpc/grpcreflect-go/assets/8893623/27989018-75fc-4f94-9d2f-22eaf27578fe">

<img width="1213" alt="image" src="https://github.com/connectrpc/grpcreflect-go/assets/8893623/55ae6052-6de9-4771-b0cb-0b64c53dd54f">

**Comment by jhump** [comment]
FWIW, grpcui has a fix for this in https://github.com/fullstorydev/grpcui/pull/314, but it's not been included in a release yet.
