### ISSUE TITLE
Namespace conflict when using grpcreflect-go with connect-go

### ISSUE THREAD

**Issue by jacobnguyenn** [connectrpc/grpcreflect-go#77]
Hi guys, thanks for the awesome tool.
However, i'm facing this problem when using grpcreflect with connect-go.
```
WARNING: proto: file "connectext/grpc/status/v1/status.proto" is already registered
	previously from: "connectrpc.com/connect/internal/gen/connectext/grpc/status/v1"
	currently from:  "github.com/bufbuild/connect-go/internal/gen/connectext/grpc/status/v1"
```

The problem can be resolved if i add `-ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"` to go run and go build command.
Is there any better way to resolve this problem ?
My version from go.mod
connectrpc.com/grpcreflect v1.2.0
github.com/bufbuild/connect-go v1.10.0

**Comment by jhump** [comment]
@jacobnguyenn, we apologize for the inconvenience, but the `github.com/bufbuild/connect*` modules and the `connectrpc.com/*` modules are not meant to be used together. The Connect RPC project is now [part of the CNCF](https://buf.build/blog/connect-rpc-joins-cncf), and part of that change meant moving the project to its own GitHub org, _out of_ [github.com/bufbuild](https://github.com/bufbuild) and _into_ [github.com/connectrpc](https://github.com/connectrpc).

The version of the `grpcreflect` package that is compatible with "github.com/bufbuild/connect-go"  is actually "github.com/bufbuild/connect-grpcreflect-go". When we moved the Connect RPC project to the connectrpc org in GitHub, we moved that to the newer  "connectrpc.com/grpcreflect" module your `go.mod` is referencing.

If you visit the old "github.com/bufbuild/connect-go" page in GitHub, you'll see that [the README](https://github.com/bufbuild/connect-go?tab=readme-ov-file#connect) indicates that connectrpc.com is the new domain for the Go import path. It also includes migration directions.

So you'll need to migrate your code to import `connectrpc.com/connect` (per the directions in the previous above) and remove `github.com/bufbuild/connect-go` from your `go.mod` file. Apologies for any disruption this causes.

**Comment by jacobnguyenn** [comment]
> @jacobnguyenn, we apologize for the inconvenience, but the `github.com/bufbuild/connect*` modules and the `connectrpc.com/*` modules are not meant to be used together. The Connect RPC project is now [part of the CNCF](https://buf.build/blog/connect-rpc-joins-cncf), and part of that change meant moving the project to its own GitHub org, _out of_ [github.com/bufbuild](https://github.com/bufbuild) and _into_ [github.com/connectrpc](https://github.com/connectrpc).
> 
> The version of the `grpcreflect` package that is compatible with "github.com/bufbuild/connect-go" is actually "github.com/bufbuild/connect-grpcreflect-go". When we moved the Connect RPC project to the connectrpc org in GitHub, we moved that to the newer "connectrpc.com/grpcreflect" module your `go.mod` is referencing.
> 
> If you visit the old "github.com/bufbuild/connect-go" page in GitHub, you'll see that [the README](https://github.com/bufbuild/connect-go?tab=readme-ov-file#connect) indicates that connectrpc.com is the new domain for the Go import path. It also includes migration directions.
> 
> So you'll need to migrate your code to import `connectrpc.com/connect` (per the directions in the previous above) and remove `github.com/bufbuild/connect-go` from your `go.mod` file. Apologies for any disruption this causes.

Thanks alot. It turns out that i need to update import `github.com/connectrpc/grpchealth-go`  to `connectrpc.com/grpchealth` to completely get rid of `connectrpc.com/connect` as indirect dependency in go.mod file
