### ISSUE TITLE
Allow setting up grpcreflection for dynamic schemas

### ISSUE THREAD

**Issue by rauanmayemir** [connectrpc/grpcreflect-go#80]
Currently `connectrpc.com/grpcreflect` will not work with dynamic schemas.
It defers to `protoregistry.GlobalFiles` and even if I want to specify my own types, it is not trivial as I have to re-type all the things from under the hood to set up a custom Reflector.

**Comment by rauanmayemir** [comment]
Correction, I cannot create a custom reflector with `staticNames` being private.

**Comment by jhump** [comment]
@rauanmayemir, the `Namer` interface is a simple single-method. You don't need `staticNames`. You can just provide your own implementation.
```go

type names []string
func (n names) Names() []string {
    return n
}
```

**Comment by rauanmayemir** [comment]
So I could actually inject my own implementation of `Reflector`, I'll try it then.

**Comment by rauanmayemir** [comment]
While I can easily re-implement the namer part, almost everything is needed to be re-implemented as well due to private types: reflector, resolver, options.

**Comment by jhump** [comment]
I don't really understand what you are trying to do. You can easily use this repo with dynamic schemas using `NewReflector` and passing `WithExtensionResolver` and `WithDescriptorResolver` options, to provide custom resolvers for your dynamic schemas. The custom `Namer` can be used to customize the names returned from `ListServices` requests.

**Comment by rauanmayemir** [comment]
Oh, let me try that. Yes, that's what I needed but only looked into the function implementations without accounting for options.

**Comment by rauanmayemir** [comment]
It turned out to be trivial, thank you. 🙌
